
package forms;

public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        ExitMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        OptionBuscar = new javax.swing.JMenu();
        LisstEmail = new javax.swing.JMenuItem();
        ItemCalculos = new javax.swing.JMenuItem();
        ListLevels = new javax.swing.JMenuItem();
        ListAll = new javax.swing.JMenuItem();
        ListSaldo = new javax.swing.JMenuItem();
        Marcas = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        desktopPane.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        ExitMenu.setMnemonic('f');
        ExitMenu.setText("Cliente");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("ABM");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        ExitMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        ExitMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        ExitMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        ExitMenu.add(exitMenuItem);

        menuBar.add(ExitMenu);

        OptionBuscar.setMnemonic('e');
        OptionBuscar.setText("Buscar");

        LisstEmail.setText("List Email");
        LisstEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LisstEmailActionPerformed(evt);
            }
        });
        OptionBuscar.add(LisstEmail);

        ItemCalculos.setText("Calculos");
        ItemCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCalculosActionPerformed(evt);
            }
        });
        OptionBuscar.add(ItemCalculos);

        ListLevels.setText("List Levels");
        ListLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListLevelsActionPerformed(evt);
            }
        });
        OptionBuscar.add(ListLevels);

        ListAll.setText("List All");
        ListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListAllActionPerformed(evt);
            }
        });
        OptionBuscar.add(ListAll);

        ListSaldo.setText("List Saldo");
        ListSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListSaldoActionPerformed(evt);
            }
        });
        OptionBuscar.add(ListSaldo);

        Marcas.setText("Marca y compañia");
        Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcasActionPerformed(evt);
            }
        });
        OptionBuscar.add(Marcas);

        menuBar.add(OptionBuscar);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        FrmCelulares abm= new FrmCelulares();
        desktopPane.add(abm);
        abm.show();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void LisstEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LisstEmailActionPerformed
     FrmListEmail listarPorEmail= new FrmListEmail();
     desktopPane.add(listarPorEmail);
     listarPorEmail.show();
             
    }//GEN-LAST:event_LisstEmailActionPerformed

    private void ItemCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCalculosActionPerformed
        // TODO add your handling code here:
        FrmCalculos calculos= new FrmCalculos();
     desktopPane.add(calculos);
     calculos.show();
    }//GEN-LAST:event_ItemCalculosActionPerformed

    private void ListLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListLevelsActionPerformed
       InFormFiltros  formNiveles = new InFormFiltros();
        desktopPane.add(formNiveles);
        formNiveles.show();
    }//GEN-LAST:event_ListLevelsActionPerformed

    private void ListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListAllActionPerformed
            InFormListarTodo  formListarTodo = new InFormListarTodo();
        desktopPane.add(formListarTodo);
        formListarTodo.show();
    }//GEN-LAST:event_ListAllActionPerformed

    private void ListSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListSaldoActionPerformed
         FrmSaldo  formListSaldo = new FrmSaldo ();
        desktopPane.add(formListSaldo);
       formListSaldo.show();
    }//GEN-LAST:event_ListSaldoActionPerformed

    private void MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcasActionPerformed
        IntFormListarCompaniaMarca formListMarcas = new IntFormListarCompaniaMarca();
        desktopPane.add(formListMarcas);
       formListMarcas.show();
    }//GEN-LAST:event_MarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ExitMenu;
    private javax.swing.JMenuItem ItemCalculos;
    private javax.swing.JMenuItem LisstEmail;
    private javax.swing.JMenuItem ListAll;
    private javax.swing.JMenuItem ListLevels;
    private javax.swing.JMenuItem ListSaldo;
    private javax.swing.JMenuItem Marcas;
    private javax.swing.JMenu OptionBuscar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
