/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import desarrolloo.FiltroNivel;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class InFormFiltros extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFormFiltros
     */
    public InFormFiltros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDerecha = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCelular = new javax.swing.JTable();
        panelFilltroNiveles = new javax.swing.JPanel();
        cbNivel0 = new javax.swing.JCheckBox();
        cbNivel1 = new javax.swing.JCheckBox();
        cbNivel2 = new javax.swing.JCheckBox();
        cbNivel3 = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        tablaCelular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2l", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tablaCelular);

        javax.swing.GroupLayout panelDerechaLayout = new javax.swing.GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelDerechaLayout.setVerticalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        cbNivel0.setText("Nivel 0");

        cbNivel1.setText("Nivel 1");

        cbNivel2.setText("Nivel 2");

        cbNivel3.setText("Nivel 3");

        btnBuscar.setText("Busca+ar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFilltroNivelesLayout = new javax.swing.GroupLayout(panelFilltroNiveles);
        panelFilltroNiveles.setLayout(panelFilltroNivelesLayout);
        panelFilltroNivelesLayout.setHorizontalGroup(
            panelFilltroNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilltroNivelesLayout.createSequentialGroup()
                .addGroup(panelFilltroNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFilltroNivelesLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(panelFilltroNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNivel3)
                            .addComponent(cbNivel2)
                            .addComponent(cbNivel1)
                            .addComponent(cbNivel0)))
                    .addGroup(panelFilltroNivelesLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnBuscar)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelFilltroNivelesLayout.setVerticalGroup(
            panelFilltroNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilltroNivelesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbNivel0)
                .addGap(18, 18, 18)
                .addComponent(cbNivel1)
                .addGap(18, 18, 18)
                .addComponent(cbNivel2)
                .addGap(18, 18, 18)
                .addComponent(cbNivel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelFilltroNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(panelFilltroNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (cbNivel0.isSelected() || cbNivel1.isSelected() || cbNivel2.isSelected() || cbNivel3.isSelected()) {
            FiltroNivel filtroNivel = new FiltroNivel();
            tablaCelular.setModel(filtroNivel.obtenerTitulos());
            tablaCelular.setModel(filtroNivel.obtenerNiveles2(cbNivel0.isSelected(), cbNivel1.isSelected(), cbNivel2.isSelected(), cbNivel3.isSelected()));
        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir al menos un nivel");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JCheckBox cbNivel0;
    private javax.swing.JCheckBox cbNivel1;
    private javax.swing.JCheckBox cbNivel2;
    private javax.swing.JCheckBox cbNivel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelFilltroNiveles;
    private javax.swing.JTable tablaCelular;
    // End of variables declaration//GEN-END:variables
}
