/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import desarrolloo.FiltrarMarcaCompania;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class IntFormListarCompaniaMarca extends javax.swing.JInternalFrame {

    /**
     * Creates new form IntFormListarCompaniaMarca
     */
    public IntFormListarCompaniaMarca() {
        initComponents();
        panelCompanias.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMarcaCompania = new javax.swing.ButtonGroup();
        buttonGroupIncluyeExcluye = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelDerecha = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCelular = new javax.swing.JTable();
        panelFiltro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioButtonMarca = new javax.swing.JRadioButton();
        radioButtonCompania = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbUsuario = new javax.swing.JCheckBox();
        cbNombre = new javax.swing.JCheckBox();
        cbTelefono = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        panelMarcas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbSamsung = new javax.swing.JCheckBox();
        cbLg = new javax.swing.JCheckBox();
        cbNokia = new javax.swing.JCheckBox();
        cbBlackberry = new javax.swing.JCheckBox();
        cbMotorola = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        radiobuttonIncluye = new javax.swing.JRadioButton();
        radioButtonExcluye = new javax.swing.JRadioButton();
        panelCompanias = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbAtyt = new javax.swing.JCheckBox();
        cbAxel = new javax.swing.JCheckBox();
        cbIUsacell = new javax.swing.JCheckBox();
        cbMovistar = new javax.swing.JCheckBox();
        cbTelcell = new javax.swing.JCheckBox();
        cbUnifon = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        tablaCelular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tablaCelular);

        javax.swing.GroupLayout panelDerechaLayout = new javax.swing.GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelDerechaLayout.setVerticalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Instrucciones de busqueda");

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        radioButtonMarca.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupMarcaCompania.add(radioButtonMarca);
        radioButtonMarca.setSelected(true);
        radioButtonMarca.setText("Marcas");
        radioButtonMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMarcaActionPerformed(evt);
            }
        });

        radioButtonCompania.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupMarcaCompania.add(radioButtonCompania);
        radioButtonCompania.setText("Compañias Telefonicas");
        radioButtonCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCompaniaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("1- Seleccione el campo del filtro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(radioButtonMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonCompania)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonMarca)
                    .addComponent(radioButtonCompania))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        cbUsuario.setBackground(new java.awt.Color(102, 153, 255));
        cbUsuario.setSelected(true);
        cbUsuario.setText("Usuario");

        cbNombre.setBackground(new java.awt.Color(102, 153, 255));
        cbNombre.setText("Nombre");

        cbTelefono.setBackground(new java.awt.Color(102, 153, 255));
        cbTelefono.setText("Telefono");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("2- Selecciones campos a mostrar en la tabla de resultado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cbUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(cbNombre)
                        .addGap(18, 18, 18)
                        .addComponent(cbTelefono))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUsuario)
                    .addComponent(cbNombre)
                    .addComponent(cbTelefono))
                .addGap(15, 15, 15))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panelMarcas.setBackground(new java.awt.Color(153, 204, 255));

        jLabel4.setText("Marcas disponibles");

        cbSamsung.setBackground(new java.awt.Color(153, 204, 255));
        cbSamsung.setText("Samsung");

        cbLg.setBackground(new java.awt.Color(153, 204, 255));
        cbLg.setText("LG");

        cbNokia.setBackground(new java.awt.Color(153, 204, 255));
        cbNokia.setText("Nokia");

        cbBlackberry.setBackground(new java.awt.Color(153, 204, 255));
        cbBlackberry.setText("Blackberry");

        cbMotorola.setBackground(new java.awt.Color(153, 204, 255));
        cbMotorola.setText("Motorola");

        javax.swing.GroupLayout panelMarcasLayout = new javax.swing.GroupLayout(panelMarcas);
        panelMarcas.setLayout(panelMarcasLayout);
        panelMarcasLayout.setHorizontalGroup(
            panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcasLayout.createSequentialGroup()
                .addGroup(panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMarcasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addGroup(panelMarcasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNokia)
                            .addComponent(cbSamsung)
                            .addComponent(cbBlackberry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addGroup(panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLg)
                            .addComponent(cbMotorola))))
                .addGap(19, 19, 19))
        );
        panelMarcasLayout.setVerticalGroup(
            panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSamsung)
                    .addComponent(cbLg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNokia)
                    .addComponent(cbMotorola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBlackberry)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("3- Seleccione una opcion de filtro...");

        radiobuttonIncluye.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupIncluyeExcluye.add(radiobuttonIncluye);
        radiobuttonIncluye.setSelected(true);
        radiobuttonIncluye.setText("Mostrar solo los que SI tienen telefono de la marca Seleccionada");

        radioButtonExcluye.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroupIncluyeExcluye.add(radioButtonExcluye);
        radioButtonExcluye.setText("Mostrar solo los que NO tienen telefonos de la marca seleccionada");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonExcluye)
                            .addComponent(radiobuttonIncluye)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(radiobuttonIncluye)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonExcluye)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCompanias.setBackground(new java.awt.Color(153, 204, 255));

        jLabel6.setText("Compañias disponibles");

        cbAtyt.setBackground(new java.awt.Color(153, 204, 255));
        cbAtyt.setText("AT&T");

        cbAxel.setBackground(new java.awt.Color(153, 204, 255));
        cbAxel.setText("AXEL");

        cbIUsacell.setBackground(new java.awt.Color(153, 204, 255));
        cbIUsacell.setText("IUSACELL");

        cbMovistar.setBackground(new java.awt.Color(153, 204, 255));
        cbMovistar.setText("MOVISTAR");

        cbTelcell.setBackground(new java.awt.Color(153, 204, 255));
        cbTelcell.setText("TELCELL");

        cbUnifon.setBackground(new java.awt.Color(153, 204, 255));
        cbUnifon.setText("UNIFON");

        javax.swing.GroupLayout panelCompaniasLayout = new javax.swing.GroupLayout(panelCompanias);
        panelCompanias.setLayout(panelCompaniasLayout);
        panelCompaniasLayout.setHorizontalGroup(
            panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompaniasLayout.createSequentialGroup()
                .addGroup(panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompaniasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTelcell)
                            .addComponent(cbAtyt)
                            .addComponent(cbIUsacell))
                        .addGap(18, 18, 18)
                        .addGroup(panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMovistar)
                            .addComponent(cbAxel)
                            .addComponent(cbUnifon)))
                    .addGroup(panelCompaniasLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelCompaniasLayout.setVerticalGroup(
            panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompaniasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAtyt)
                    .addComponent(cbAxel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTelcell)
                    .addComponent(cbUnifon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCompaniasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbIUsacell)
                    .addComponent(cbMovistar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFiltroLayout.createSequentialGroup()
                            .addComponent(panelMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(panelCompanias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCompanias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMarcas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBuscar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Buscar clientes filtrando por marca o compañia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if ((!cbUsuario.isSelected()) && (!cbNombre.isSelected()) && (!cbTelefono.isSelected())) {
            JOptionPane.showMessageDialog(null, "Debe elegir al menos un campo a mostrar en la tabla de resultado");
        } else {
            boolean error = false;
            if (radioButtonMarca.isSelected()) {
                if ((!cbSamsung.isSelected()) && (!cbLg.isSelected()) && (!cbNokia.isSelected()) && (!cbMotorola.isSelected()) && (!cbBlackberry.isSelected())) {
                    JOptionPane.showMessageDialog(null, "Debe elegir al menos una marca");
                    error = true;
                }
            } else {
                if ((!cbAtyt.isSelected()) && (!cbAxel.isSelected()) && (!cbTelcell.isSelected()) && (!cbUnifon.isSelected()) && (!cbIUsacell.isSelected()) && (!cbMovistar.isSelected())) {
                    JOptionPane.showMessageDialog(null, "Debe elegir al menos una compañia telefonica");
                    error = true;
                }
            }
            if (!error) {
                FiltrarMarcaCompania clienteBusqueda = new  FiltrarMarcaCompania();
                tablaCelular.setModel(clienteBusqueda.obtenerTitulos(cbUsuario.isSelected(), cbNombre.isSelected(), cbTelefono.isSelected()));
                tablaCelular.setModel(clienteBusqueda.busquedaPersonalizada(cbUsuario.isSelected(), cbNombre.isSelected(), cbTelefono.isSelected(), radioButtonMarca.isSelected(), radiobuttonIncluye.isSelected(), cbSamsung.isSelected(), cbLg.isSelected(), cbNokia.isSelected(), cbMotorola.isSelected(), cbBlackberry.isSelected(), cbAtyt.isSelected(), cbAxel.isSelected(), cbTelcell.isSelected(), cbUnifon.isSelected(), cbIUsacell.isSelected(), cbMovistar.isSelected()));
            }
        }

        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void radioButtonMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMarcaActionPerformed
        // TODO add your handling code here:
        panelMarcas.setVisible(true);
        panelCompanias.setVisible(false);
        radiobuttonIncluye.setText("Mostrar solo los que SI tienen telefono de la marca Seleccionada");
        radioButtonExcluye.setText("Mostrar solo los que NO tienen telefonos de la marca seleccionada");
    }//GEN-LAST:event_radioButtonMarcaActionPerformed

    private void radioButtonCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCompaniaActionPerformed
        // TODO add your handling code here:
        panelCompanias.setVisible(true);
        panelMarcas.setVisible(false);
        radiobuttonIncluye.setText("Mostrar solo los que SI tienen las compañias seleccionadas");
        radioButtonExcluye.setText("Mostrar solo los que NO tienen las compañias seleccionada");
    }//GEN-LAST:event_radioButtonCompaniaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup buttonGroupIncluyeExcluye;
    private javax.swing.ButtonGroup buttonGroupMarcaCompania;
    private javax.swing.JCheckBox cbAtyt;
    private javax.swing.JCheckBox cbAxel;
    private javax.swing.JCheckBox cbBlackberry;
    private javax.swing.JCheckBox cbIUsacell;
    private javax.swing.JCheckBox cbLg;
    private javax.swing.JCheckBox cbMotorola;
    private javax.swing.JCheckBox cbMovistar;
    private javax.swing.JCheckBox cbNokia;
    private javax.swing.JCheckBox cbNombre;
    private javax.swing.JCheckBox cbSamsung;
    private javax.swing.JCheckBox cbTelcell;
    private javax.swing.JCheckBox cbTelefono;
    private javax.swing.JCheckBox cbUnifon;
    private javax.swing.JCheckBox cbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCompanias;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelMarcas;
    private javax.swing.JRadioButton radioButtonCompania;
    private javax.swing.JRadioButton radioButtonExcluye;
    private javax.swing.JRadioButton radioButtonMarca;
    private javax.swing.JRadioButton radiobuttonIncluye;
    private javax.swing.JTable tablaCelular;
    // End of variables declaration//GEN-END:variables
}
